### PR TITLE
Serial rewrite

### PR DESCRIPTION
**Pull request by chasester**
Basic approval

### CODE REVIEW

**Comment by api-Hypernova** [comment]
Looks fine, go ahead and merge.

**Review by api-Hypernova — COMMENTED** [review]
I don't think we should keep binaries in git. The git history will become huge very quickly with these objects, git doesn't manage VC well with them.

**Comment by chasester** [comment]
ya this isnt ready to merge and yes ill add them to the ignore list

@edit
fixed: 5d5e40c

**Comment by chasester** [comment]
Broken do not use

**Pull request closed without merging**
